import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#0c1322",
        foreground: "#dce2f7",
        "surface-bright": "#323949",
        "on-tertiary-fixed": "#0e1c2f",
        "secondary-fixed": "#dce2f3",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-container": "#aeb5c5",
        "on-error": "#690005",
        "primary-container": "#1a52c7",
        "inverse-primary": "#2056cb",
        "surface-container-low": "#141b2b",
        "outline": "#8d909f",
        "primary": "#b4c5ff",
        "surface-container-high": "#232a3a",
        "surface-tint": "#b4c5ff",
        "surface-dim": "#0c1322",
        "primary-fixed": "#dbe1ff",
        "surface-variant": "#2e3545",
        "on-surface": "#dce2f7",
        "tertiary-fixed": "#d5e3fe",
        "on-tertiary": "#233145",
        "on-primary-container": "#c5d2ff",
        "tertiary": "#b9c7e1",
        "on-background": "#dce2f7",
        "on-secondary": "#2a313d",
        "error": "#ffb4ab",
        "secondary-container": "#404754",
        "tertiary-fixed-dim": "#b9c7e1",
        "on-primary-fixed": "#00174a",
        "on-primary": "#002a77",
        "surface-container-lowest": "#070e1d",
        "on-tertiary-container": "#c5d3ee",
        "on-surface-variant": "#c3c6d6",
        "on-secondary-fixed": "#151c27",
        "on-tertiary-fixed-variant": "#3a475d",
        "secondary": "#c0c7d6",
        "inverse-on-surface": "#293040",
        "tertiary-container": "#4e5b72",
        "secondary-fixed-dim": "#c0c7d6",
        "on-secondary-fixed-variant": "#404754",
        "outline-variant": "#434654",
        "surface-container-highest": "#2e3545",
        "inverse-surface": "#dce2f7",
        "surface-container": "#191f2f",
        "surface": "#0c1322",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#003ea7",
        "on-error-container": "#ffdad6",
        border: "#434654",
        input: "#434654",
        ring: "#b4c5ff",
      },

      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
        headline: ["var(--font-sans)", "sans-serif"],
        body: ["var(--font-sans)", "sans-serif"],
        label: ["var(--font-sans)", "sans-serif"],
        mono: ["var(--font-sans)", "sans-serif"],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
